### ISSUE TITLE
C# Header Section

### ISSUE THREAD

**Issue by codyj110** [codyj110/gedcom-whisperer#3]
as a gedcom reader i need the ability to parse the header section of loaded gedcom file, so I can later edit or view data.

**Comment by patwalt** [comment]
@codyj110 , Can you check in a sample gedcom file so we can build a "header" section (and other sections)?

**Comment by codyj110** [comment]
you can check in another the sample of if you want they are available at https://www.gedcom.org/   didn't think it needed anymore it but if you want it go ahead and check it in. Also look like you accidentally closed this @patwalt
